displayName=Zero XP Drops
author=Domin
support=https://github.com/Sintry1/zero-xp-drops/issues
description=Scrolling blue hitsplat and zero for detected combat attacks without damage XP
tags=combat,xp,zero,miss,hitsplat
plugins=com.zeroxpdrops.ZeroXpDropsPlugin
